export const productImg = [
  'https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/1.webp',
  'https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/1.webp',
  'https://cdn.dummyjson.com/product-images/beauty/powder-canister/1.webp',
  'https://cdn.dummyjson.com/product-images/beauty/red-lipstick/1.web',
  'https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/1.webp',
  'https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp',
  'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/thumbnail.webp',
  'https://cdn.dummyjson.com/product-images/groceries/kiwi/1.webp',
  'https://cdn.dummyjson.com/product-images/groceries/juice/1.webp',
  'https://cdn.dummyjson.com/product-images/groceries/ice-cream/1.webp',
  'https://cdn.dummyjson.com/product-images/groceries/honey-jar/1.webp',
  'https://cdn.dummyjson.com/product-images/groceries/green-chili-pepper/1.webp',
  'https://cdn.dummyjson.com/product-images/groceries/green-bell-pepper/1.webp',
  'https://cdn.dummyjson.com/product-images/groceries/fish-steak/1.webp',
  'https://cdn.dummyjson.com/product-images/groceries/eggs/1.webp',
  'https://cdn.dummyjson.com/product-images/groceries/dog-food/1.webp',
  'https://cdn.dummyjson.com/product-images/groceries/cooking-oil/1.webp',
  'https://cdn.dummyjson.com/product-images/groceries/chicken-meat/1.webp',
  'https://cdn.dummyjson.com/product-images/groceries/chicken-meat/2.webp',
  'https://cdn.dummyjson.com/product-images/groceries/beef-steak/1.webp',
  'https://cdn.dummyjson.com/product-images/fragrances/dior-j adore/1.webp',
  'https://cdn.dummyjson.com/product-images/fragrances/dior-j adore/2.webp',
  'https://cdn.dummyjson.com/product-images/fragrances/dior-j adore/3.webp'
];
